export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_PARTIES_DATA = "SET_PARTIES_DATA";
export const SET_CANDIDATES_DATA = "SET_CANDIDATES_DATA";
export const SET_VOTERS_DATA = "SET_VOTERS_DATA";
export const SET_POSITIONS_DATA = "SET_POSITIONS_DATA";
export const UPDATE_TIME_STATE = "UPDATE_TIME_STATE";
export const UPDATE_ALREADY_VOTED = "UPDATE_ALREADY_VOTED";